<?php
/**
 * Yes, this is a module.
 */

require_once __DIR__.'/nodesearch.element.inc';
require_once __DIR__.'/nodesearch.field.inc';

/**
 * Implements hook_menu().
 */
function nodesearch_menu() {
  return [
    'ajax/node/search' => [
      'page callback'     => 'sf_dic_page',
      'page arguments'    => [\MakinaCorpus\Drupal\NodeSearch\EndpointController::class.'::search'],
      'access callback'   => true,
      'type'              => MENU_CALLBACK,
    ],
    'node/search/test' => [
      'page callback'     => 'drupal_get_form',
      'page arguments'    => ['nodesearch_page_test_form'],
      'access arguments'  => ['this permission does not exist, this is for admin'],
      'type'              => MENU_CALLBACK,
      'file'              => 'nodesearch.example.inc',
    ],
  ];
}

/**
 * Get entity bundle label
 */
function nodesearch_bundle_label(string $entityType, $entity): string {
  if (is_string($entity)) {
    $bundle = $entity;
  } else {
    list(,, $bundle) = entity_extract_ids($entityType, $entity);
  }
  return entity_get_info($entityType)['bundles'][$bundle]['label'] ?? $bundle;
}

/**
 * Implements hook_library().
 */
function nodesearch_library() {
  $libraries = [];

  $embedReact = variable_get('nodesearch_react_enable', true) && !module_exists('react');
  if (null === ($useDev = variable_get('nodesearch_dev_mode', null))) {
    $useDev = (0 < variable_get('error_log'));
  }

  if ($embedReact) {
    if ($useDev) {
      $libraries['react'] = [
        'title' => 'React',
        'website' => 'https://reactjs.org/',
        'version' => '16.*',
        'js' => [
          'https://unpkg.com/react@16/umd/react.production.min.js' => ['external' => true],
          'https://unpkg.com/react-dom@16/umd/react-dom.production.min.js' => ['external' => true],
        ],
      ];
    } else{
      $libraries['react'] = [
        'title' => 'React',
        'website' => 'https://reactjs.org/',
        'version' => '16.*',
        'js' => [
          'https://unpkg.com/react@16/umd/react.development.js' => ['external' => true],
          'https://unpkg.com/react-dom@16/umd/react-dom.development.js' => ['external' => true],
        ],
      ];
    }
  }

  $path = drupal_get_path('module', 'nodesearch');

  $libraries['nodesearch'] = [
    'title' => 'Node search',
    'website' => 'https://github.com/makinacorpus/drupal-nodesearch',
    'version' => '1',
    'js' => [
      $path . '/dist/nodesearch.js' => [],
      $path . '/dist/behavior.js' => [],
    ],
    'css' => [
      $path . '/dist/nodesearch.css' => [],
    ],
  ];

  if ($embedReact) {
    $libraries['nodesearch']['dependencies'][] = ['nodesearch', 'react'];
  }

  return $libraries;
}
